name: Gmail Invoices

on:
  schedule:
    - cron: "0 7-23 * * *"   # every 60 min, 07:00–23:00
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Restore credentials/secrets
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" > ~/.config/rclone/rclone.conf
          echo "${{ secrets.GMAIL_CREDENTIALS_JSON }}" > gmail_credentials.json
          echo "${{ secrets.GMAIL_TOKEN_JSON }}" > token.json

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test rclone (optional)
        run: rclone lsf onedrive:

      - name: Run GmailHelper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_REPORT_TO: ${{ secrets.GMAIL_REPORT_TO }}
          PYTHONUNBUFFERED: "1"
        run: python -u GmailHelper.py
