name: Gmail Invoices

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      RCLONE_BIN_VERSION: "v1.67.0"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache rclone
        id: cache-rclone
        uses: actions/cache@v4
        with:
          path: ~/.local/bin
          key: rclone-${{ runner.os }}-${{ env.RCLONE_BIN_VERSION }}

      - name: Install rclone (if missing)
        if: steps.cache-rclone.outputs.cache-hit != 'true'
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$HOME/.local/bin"
          curl -fsSL "https://downloads.rclone.org/${RCLONE_BIN_VERSION}/rclone-${RCLONE_BIN_VERSION}-linux-amd64.zip" -o /tmp/rclone.zip
          unzip -j /tmp/rclone.zip "rclone-*/rclone" -d "$HOME/.local/bin"
          chmod +x "$HOME/.local/bin/rclone"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Restore credentials/secrets
        shell: bash
        run: |
          set -euo pipefail

          # rclone (base64)
          mkdir -p "$HOME/.config/rclone"
          echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > "$HOME/.config/rclone/rclone.conf"
          chmod 600 "$HOME/.config/rclone/rclone.conf"

          # gmail (base64)
          echo "${{ secrets.GMAIL_CREDENTIALS_JSON_B64 }}" | base64 -d > gmail_credentials.json
          echo "${{ secrets.GMAIL_TOKEN_JSON_B64 }}"       | base64 -d > token.json
          chmod 600 gmail_credentials.json token.json

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test rclone (silent)
        shell: bash
        continue-on-error: true
        run: |
          export RCLONE_CONFIG="$HOME/.config/rclone/rclone.conf"
          rclone about "onedrive:" --log-level ERROR >/dev/null

      - name: Run GmailHelper
        shell: bash
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PYTHONUNBUFFERED: "1"
        run: |
          unset HTTP_PROXY HTTPS_PROXY ALL_PROXY http_proxy https_proxy all_proxy
          python -u GmailHelper.py
