name: Gmail Invoices

on:
  schedule:
    - cron: "*/30 7-23 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install rclone
        run: |
          sudo apt-get update
          sudo apt-get install -y rclone

      - name: Restore credentials/secrets
        run: |
          mkdir -p ~/.config/rclone
          echo '${{ secrets.RCLONE_CONF }}' > ~/.config/rclone/rclone.conf
          echo '${{ secrets.GMAIL_CREDENTIALS_JSON }}' > gmail_credentials.json
          echo '${{ secrets.GMAIL_TOKEN_JSON }}' > token.json
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Smoke test rclone (optional)
        run: |
            mkdir -p ~/.config/rclone
            echo "${{ secrets.RCLONE_CONF_B64 }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib pydantic openai

      - name: Run GmailHelper
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python -u GmailHelper.py
